name: Linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependecies
      run: make install 
    
    - name: Run Eslint
      run: make lint

    - name: Test and code coverages!
      uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE_TEST_ID }}